nie.util.share_traceCome=nie.util.share_traceCome||!1;nie.util.share_css=nie.util.share_css||!1;
(function(c){nie.util.share=nie.util.share||function(){var x=function(a){c(new Image).bind("readystatechange",function(){}).bind("abort",function(){}).attr("src",a)},q=function(a,c,e,g){e=null!=b.args[a]?b.args[a]:e;if(""==e)return e;"url"==a&&(a=e,(e=a.match(b.args.urlReg))?e=a.replace(e[0],e[1]+[c,b.args.product,b.args.traceType].join()):(a=z(a),c=a.search+(""==a.search?"?":"&")+"nieShare="+[c,b.args.product,b.args.traceType].join(),e=/^\//.test(a.pathname)?a.pathname:"/"+a.pathname,e=a.protocol+
"//"+(80==a.port?a.hostname:a.host)+e+c+a.hash));return encodeURIComponent(e+("undefined"!=typeof g?g:""))},w=function(a){var b=[],c;for(c in a)b.push(c+"="+a[c]);return b},z=function(a){var b=document.createElement("div");b.innerHTML='<a href="'+a.replace(/"/g,"%22")+'"/>';return b.firstChild},b={data:{},args:{panelID:"NIE-share-panel",fat:"#NIE-share",product:nie.config.site,imgs:null,txt:null,type:1,traceType:null,imgSize:[100,100],defShow:[23,22,5,2,1,4],defShow2:[23,22,5,2,1,4,3,8],moreShow:[23,
22,5,1,2,3,4,6,7,8,9,10,11,13],searchTips:"\u8f93\u5165\u7f51\u7ad9\u540d\u6216\u62fc\u97f3\u7f29\u5199",sideBar_top:100,title:null,url:null,img:null,content:null,urlReg:/([&?]nieShare=)(\d+),([^,]+),(\d+)/},addBtn:function(a,d,e,g,k,h){var r="",n="";a=parseInt(a);var s="",l="",m=0,t=20;switch("undefined"!=typeof h?h:b.args.type){case 1:m=-(d-20+5*(a-1)+20*(a-1));22==a?m=-325:"";23==a?m=-350:"";break;case 2:m=40*-(a-1)-80;22==a?m=-40:"";23==a?m=-0:"";t=36;break;case 3:m=-(d-16+6*(a+1)+16*(a+1))}d=
"background-position:"+e+"px "+m+"px";!0==k?(r=b.data[a].name,n="\u5206\u4eab\u5230"+r,l=d):!1==k?(n="\u5206\u4eab\u5230"+b.data[a].name,s="<img width="+t+" height="+t+" src='http://res.nie.netease.com/comm/blank.gif' style='"+d+"'>"):(r=k,l=d);k={index:a,"class":6==b.args.type?"NIE-share":"",style:l,href:"javascript:;",title:n,target:"_self"};""==s?k.text=r:k.html=s;var f=c("<a>",k).appendTo(g);(function(){var c=a;f.click(function(){if(b.data[c]){var a=b.data[c],e=q("url",c,location.href),d=q("title",
c,document.title),g=q("img",c,""),k=q("content",c,document.title),p;p=[650,500];22==c?p=[460,380]:"";23==c?p=[573,600]:"";p=w({width:p[0],height:p[1],top:(screen.height-p[1])/4,left:(screen.width-p[0])/2,toolbar:"no",menubar:"no",scrollbars:"no",resizable:"yes",location:"no",status:"no"});for(var f in a.paramName){var h="";switch(parseInt(f)){case 1:h=e;break;case 2:h=5==c?d+e:d;break;case 3:h=g;break;case 4:h=k;break;case 5:h=encodeURIComponent(nie.util.siteName())}a.params[a.paramName[f]]=h}a="http://"+
a.file+"?"+w(a.params).join("&");window.open(a,"_blank",p.join(","));x("http://click.ku.163.com/share.v2.gif?"+["product="+b.args.product,"id="+c,"type="+b.args.traceType].join("&"))}}).addClass("NIE-share-btn"+c)})();return f},addPanel:function(){var a=c("<div>",{id:b.args.panelID,html:"<h3>\u5206\u4eab\u5230...</h3><input type=text value='"+b.args.searchTips+"'/><div></div>"}).hide().appendTo(c(document.body));c("<button>").click(function(){a.hide()}).hover(function(){c(this).addClass("hover")},
function(){c(this).removeClass("hover")}).appendTo(a);var d=a.find("div"),e;for(e in b.data)b.addBtn(e,12,5,d,!0,1);a.find("input").click(function(){var a=c(this);a.val()==b.args.searchTips&&a.val("")}).keyup(function(){var a=c(this).val().toLowerCase();d.find("a").each(function(){var e=c(this),d=e.attr("index");-1!=b.data[d].name.toLowerCase().indexOf(a)||-1!=b.data[d].searchTxt.toLowerCase().indexOf(a)||-1!=b.data[d].searchTxt.replace(/[a-z]/g,"").toLowerCase().indexOf(a)?e.show():e.hide()})})},
showPanel:function(){var a="#"+b.args.panelID,d=c(a),e=c(window);0==d.length&&b.addPanel();d=c(a);a=e.scrollTop()+(e.height()-d.height())/2;d.css({top:0>a?0:a,left:(e.width()-d.width())/2}).show().find("a").show()},render:function(){var a=b.args.type;null==b.args.traceType&&(b.args.traceType=a);if(1==a||2==a){var d=c(b.args.fat);if(0<d.length){var e=c("<span>",{"class":"NIE-share NIE-share"+a,html:"<span class='NIE-share-txt'>\u5206\u4eab\u5230:</span>"}).appendTo(d),g=c("<span>",{"class":"NIE-share-iconBtn"}).appendTo(e);
c.browser.webkit&&g.css("fontSize",2==a?"41px":"20px");c.each(b.args.defShow,function(a){b.addBtn(this,20,0,g,!1)});var k=!0,h,a=c("<span>",{html:"<em></em>","class":"NIE-share-more"}).mouseenter(function(){clearTimeout(h);k=!0;var a=c(window),b=c(this).children("span"),d=b.outerHeight(),f=b.outerWidth(),g=e.offset();b.css({top:a.scrollTop()+a.height()<g.top+d+20?-d-12:4,left:a.scrollLeft()+a.width()<g.left+e.width()+f?-f+42:0}).fadeIn("fast")}).mouseleave(function(){clearTimeout(h);k=!1;h=setTimeout(function(){k||
r.fadeOut("fast")},500)}).appendTo(e),r=c("<span>").appendTo(a);c.each(b.args.moreShow,function(){b.addBtn(this,20,5,r,!0,1)})}}else if(3==a){var n=!1,s=!1,l=c("<div>",{id:"NIE-share-sideBar",html:"<div><b></b><span><button></button><h3>\u5206\u4eab\u5230...</h3><p></p></span></div>",mouseleave:function(){n&&(clearTimeout(h),s=!1,h=setTimeout(function(){s||(l.animate({width:30},500),t.animate({right:-120},500,function(){n=!1}))},1E3))},mouseenter:function(){n&&(clearTimeout(h),s=!0)}}).appendTo(c(document.body)),
m=l.find("p"),t=l.find("div"),a=function(){l.css("top",c(window).scrollTop()+b.args.sideBar_top)};c.each(b.args.moreShow,function(){b.addBtn(this,20,5,m,!0,1)});l.find("b").hover(function(){n||(n=!0,l.animate({width:150},500),t.animate({right:0},500))});l.find("button").click(function(){t.animate({right:-150},500,function(){l.remove()})}).hover(function(){c(this).addClass("hover")},function(){c(this).removeClass("hover")});c.browser.msie&&6>=c.browser.msie?(c(window).scroll(a),a()):l.css({position:"fixed",
top:b.args.sideBar_top})}else if(4==a&&b.args.imgs){var a="NIE-share-img",f=c("#"+a),d=0<f.length,u,v=!1,q=function(a){return b.args.imgSize[0]<a.outerWidth()&&b.args.imgSize[1]<a.outerHeight()};c(b.args.imgs).hover(function(){var a=c(this),e=a.outerHeight(),d=a.offset(),g=c(window),h=f.outerHeight();q(a)&&(clearTimeout(u),v=!0,b.args.img=z(a.attr("src")).href,f.find(".NIE-share-more>span").hide(),f.css({top:d.top+e>g.scrollTop()+g.height()?d.top+10:d.top+e-10-h,left:d.left+10}).show())},function(){var a=
c(this);q(a)&&(v=!1,clearTimeout(u),u=setTimeout(function(){v||f.hide()},500))});b.args.defShow=b.args.defShow2;d||(f=c("<div>",{id:a,mouseenter:function(){clearTimeout(u);v=!0},mouseleave:function(){v=!1;clearTimeout(u);u=setTimeout(function(){v||f.hide()},500)}}).appendTo(c(document.body)),b.args.type=1,b.args.fat=f,arguments.callee())}else if(5==a&&b.args.txt){var a="NIE-share-txt",f=c("#"+a),d=0<f.length,y=!1,x=c(b.args.txt),w=function(){var a="";window.getSelection?a=window.getSelection():document.getSelection?
a=document.getSelection():document.selection&&(a=document.selection.createRange().text);return c.trim(a)};b.args.defShow=b.args.defShow2;d||(f=c("<div>",{id:a}).appendTo(c(document.body)),x.mouseup(function(a){setTimeout(function(){var d=c.trim(w());y&&""!=d?(b.args.content=b.args.title=d,f.css({top:a.pageY+15,left:a.pageX-50}).show()):f.hide()},100)}).mouseleave(function(){y=!1}).mouseenter(function(){y=!0}),c(document.body).mouseup(function(){y||""!=c.trim(w())||f.hide()}),b.args.type=1,b.args.fat=
f,arguments.callee())}else 6==a&&c.each(b.args.defShow,function(){b.addBtn(this,20,0,b.args.fat,!0,1)})}};b.init=function(){if(""!=location.search&&!nie.util.share_traceCome){var a=location.search.match(b.args.urlReg);a&&(nie.util.share_traceCome=!0,x("http://click.ku.163.com/share.income.gif?"+["id="+a[2],"product="+a[3],"type="+a[4],"_r="+(new Date).getMilliseconds()].join("&")))}a=[[23,"\u6613\u4fe1\u4e8c\u7ef4\u7801","YiXinQrCode","res.nie.netease.com/comm/js/nie/util/share/api/",{1:"url",2:"title"}],
[22,"\u6613\u4fe1","YiXin","open.yixin.im/share",{1:"url",2:"title",3:"pic",4:"desc"},{appkey:"yx3ae08a776bf04178a583cb745fb6aa0c",type:"webpage"}],[1,"QQ\u7a7a\u95f4","QQKongJian","sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey",{1:"url",2:"title",3:"pics",4:"desc"}],[2,"\u65b0\u6d6a\u5fae\u535a","XinLangWeiBo","v.t.sina.com.cn/share/share.php",{1:"url",2:"title",3:"pic"},{c:"nie",content:"gb2312",source:"nie"}],[3,"\u817e\u8baf\u5fae\u535a","TengXunWeiBo","v.t.qq.com/share/share.php",{1:"url",
2:"title",3:"pic"}],[4,"\u817e\u8baf\u670b\u53cb","TengXunPengYou","sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey",{1:"url",2:"title",3:"pics",4:"desc"},{to:"pengyou"}],[5,"\u7f51\u6613\u5fae\u535a","WangYiWeiBo","t.163.com/article/user/checkLogin.do",{1:"link",2:"info",3:"images",5:"source"},{check1stImg:!0,togImg:!0,key:"OELT16LMxo0rAmtO"}],[6,"\u641c\u72d0\u5fae\u535a","SouHuWeiBo","t.sohu.com/third/post.jsp",{1:"url",2:"title",3:"pic"},{content:"utf-8"}],[7,"\u5f00\u5fc3\u7f51","KaiXinWang",
"www.kaixin001.com/repaste/share.php",{1:"rurl",2:"rtitle",4:"rcontent"}],[8,"\u4eba\u4eba\u7f51","RenRenWang","share.renren.com/share/buttonshare.do",{1:"link",2:"title"}],[9,"\u641c\u72d0\u767d\u793e\u4f1a","SouHuBaiSheHui","bai.sohu.com/share/blank/add.do",{1:"link",2:"title"}],[10,"\u6dd8\u6c5f\u6e56","TaoJiangHu","share.jianghu.taobao.com/share/addShare.htm",{1:"url",2:"title",4:"content"}],[11,"\u8c46\u74e3","DouBan","www.douban.com/recommend/",{1:"url",2:"title",3:"image"}],[13,"\u767e\u5ea6Hi",
"BaiDuHi","apps.hi.baidu.com/share/",{1:"url",2:"title",4:"content"}],[14,"\u767e\u5ea6\u8d34\u5427","BaiDuTieBa","tieba.baidu.com/i/app/open_share_api",{1:"link"}],[15,"\u767e\u5ea6\u641c\u85cf","BaiDuShouChang","cang.baidu.com/do/add",{1:"iu",2:"it",4:"dc"},{fr:"ien"}],[16,"\u996d\u5426","FangFou","fanfou.com/sharer",{1:"u",2:"t",4:"d"}],[17,"MSN","Msn","profile.live.com/badge",{1:"url",2:"title",3:"screenshot",4:"description"},{wa:"wsignin1.0"}],[18,"\u5929\u6daf\u793e\u533a","TianYaSheQu","share.tianya.cn/openapp/restpage/activity/appendDiv.jsp",
{1:"ccUrl",2:"ccTitle",4:"ccBody"}],[19,"\u51e4\u51f0\u7f51\u5fae\u535a","FengHuangWangWeiBo","t.ifeng.com/interface.php",{1:"sourceUrl",2:"title",3:"pic"},{_c:"share",_a:"share"}],[20,"139\u8bf4\u5ba2","139ShuoKe","shequ.10086.cn/share/share.php",{1:"tourl",2:"title"}],[21,"\u68a6\u5e7b\u4eba\u751f","MengHuanRenSheng","dream.163.com/share/link/",{1:"url",2:"title",4:"content"}]];nie.util.share_css||(c.include("share.v3.css"),nie.util.share_css=!0);var d=arguments;if(0<d.length&&0<d[0].length){var d=
d[0][0],e;for(e in d)"undefined"!=typeof d[e]&&(b.args[e]=d[e])}e=0;for(d=a.length;e<d;e++){var g=a[e],k=g[5],h={};b.data[g[0]]={name:g[1],searchTxt:g[2],file:g[3],paramName:g[4],params:"undefined"!=typeof k?k:h}}b.render()}(arguments);return b}})(jQuery);
