nie.util.share_traceCome=nie.util.share_traceCome||!1;nie.util.share_css=nie.util.share_css||!1;
(function(c){nie.util.share=nie.util.share||function(){var v=function(a){c(new Image).bind("readystatechange",function(){}).bind("abort",function(){}).attr("src",a)},m=function(a,c,e,f){e=b.args[a]!=null?b.args[a]:e;return e==""?e:(a=="url"&&(a=e,(e=a.match(b.args.urlReg))?e=a.replace(e[0],e[1]+[c,b.args.product,b.args.traceType].join(",")):(a=x(a),c=a.search+(a.search==""?"?":"&")+"nieShare="+[c,b.args.product,b.args.traceType].join(","),e=/^\//.test(a.pathname)?a.pathname:"/"+a.pathname,e=a.protocol+
"//"+(a.port==80?a.hostname:a.host)+e+c+a.hash)),encodeURIComponent(e+(typeof f!="undefined"?f:"")))},u=function(a){var b=[],c;for(c in a)b.push(c+"="+a[c]);return b},x=function(a){var b=document.createElement("div");b.innerHTML='<a href="'+a.replace(/"/g,"%22")+'"/>';return b.firstChild},b={data:{},args:{panelID:"NIE-share-panel",fat:"#NIE-share",product:nie.config.site,imgs:null,txt:null,type:1,traceType:null,imgSize:[100,100],defShow:[22,1,2,3],defShow2:[22,1,2,3,8,4],moreShow:[22,5,1,2,3,4,6,
7,8,9,10,11,13],searchTips:"\u8f93\u5165\u7f51\u7ad9\u540d\u6216\u62fc\u97f3\u7f29\u5199",sideBar_top:100,title:null,url:null,img:null,content:null,urlReg:/([&?]nieShare=)(\d+),([^,]+),(\d+)/},addBtn:function(a,d,e,f,h,j){var k="",l="",a=parseInt(a),n="",i="",o=0,p=16;switch(typeof j!="undefined"?j:b.args.type){case 1:o=-(d-16+(a+1)*6+(a+1)*16);break;case 2:o=a==22?-160:-a*32;p=32;break;case 3:o=-(d-16+(a+1)*6+(a+1)*16)}d="background-position:"+e+"px "+o+"px";h==!0?(k=b.data[a].name,l="\u5206\u4eab\u5230"+
k,i=d):h==!1?(l="\u5206\u4eab\u5230"+b.data[a].name,n="<img width="+p+" height="+p+" src='http://res.nie.netease.com/comm/blank.gif' style='"+d+"'>"):(k=h,i=d);h={index:a,"class":b.args.type==6?"NIE-share":"",style:i,href:"javascript:;",title:l,target:"_self"};n==""?h.text=k:h.html=n;var g=c("<a>",h).appendTo(f);(function(){var c=a;g.click(function(){if(b.data[c]){var a=b.data[c],e=m("url",c,location.href),d=m("title",c,document.title),f=m("img",c,""),g=m("content",c,document.title),s=c==22?[460,
380]:[650,500],s=u({width:s[0],height:s[1],top:(screen.height-s[1])/4,left:(screen.width-s[0])/2,toolbar:"no",menubar:"no",scrollbars:"no",resizable:"yes",location:"no",status:"no"}),h;for(h in a.paramName){var t="";switch(parseInt(h)){case 1:t=e;break;case 2:t=c==5?d+e:d;break;case 3:t=f;break;case 4:t=g;break;case 5:t=encodeURIComponent(nie.util.siteName())}a.params[a.paramName[h]]=t}a="http://"+a.file+"?"+u(a.params).join("&");window.open(a,"_blank",s.join(","));v("http://click.ku.163.com/share.v2.gif?"+
["product="+b.args.product,"id="+c,"type="+b.args.traceType].join("&"))}})})();return g},addPanel:function(){var a=c("<div>",{id:b.args.panelID,html:"<h3>\u5206\u4eab\u5230...</h3><input type=text value='"+b.args.searchTips+"'/><div></div>"}).hide().appendTo(c(document.body));c("<button>").click(function(){a.hide()}).hover(function(){c(this).addClass("hover")},function(){c(this).removeClass("hover")}).appendTo(a);var d=a.find("div"),e;for(e in b.data)b.addBtn(e,12,5,d,!0,1);a.find("input").click(function(){var a=
c(this);a.val()==b.args.searchTips&&a.val("")}).keyup(function(){var a=c(this).val().toLowerCase();d.find("a").each(function(){var e=c(this),d=e.attr("index");b.data[d].name.toLowerCase().indexOf(a)!=-1||b.data[d].searchTxt.toLowerCase().indexOf(a)!=-1||b.data[d].searchTxt.replace(/[a-z]/g,"").toLowerCase().indexOf(a)!=-1?e.show():e.hide()})})},showPanel:function(){var a="#"+b.args.panelID,d=c(a),e=c(window);d.length==0&&b.addPanel();d=c(a);a=e.scrollTop()+(e.height()-d.height())/2;d.css({top:a<0?
0:a,left:(e.width()-d.width())/2}).show().find("a").show()},render:function(){var a=b.args.type;if(b.args.traceType==null)b.args.traceType=a;if(a==1||a==2){var d=c(b.args.fat);if(d.length>0){var e=c("<span>",{"class":"NIE-share NIE-share"+a,html:"<span class='NIE-share-txt'>\u5206\u4eab\u5230:</span>"}).appendTo(d),f=c("<span>",{"class":"NIE-share-iconBtn"}).appendTo(e);c.browser.webkit&&f.css("fontSize",a==2?"41px":"20px");c.each(b.args.defShow,function(){b.addBtn(this,16,0,f,!1)});var h=!0,j,a=
c("<span>",{html:"<em>\u66f4\u591a</em>","class":"NIE-share-more"}).mouseenter(function(){clearTimeout(j);h=!0;var a=c(window),b=c(this).children("span"),d=b.outerHeight(),g=b.outerWidth(),f=e.offset();b.css({top:a.scrollTop()+a.height()<f.top+d+20?-d-12:4,left:a.scrollLeft()+a.width()<f.left+e.width()+g?-g+42:0}).fadeIn("fast")}).mouseleave(function(){clearTimeout(j);h=!1;j=setTimeout(function(){h||k.fadeOut("fast")},500)}).appendTo(e),k=c("<span>").appendTo(a);c.each(b.args.moreShow,function(){b.addBtn(this,
12,5,k,!0,1)});b.addBtn(-1,12,5,k,"\u66f4\u591a...",1).click(function(){k.fadeOut("fast");b.showPanel()})}}else if(a==3){var l=!1,n=!1,i=c("<div>",{id:"NIE-share-sideBar",html:"<div><b></b><span><button></button><h3>\u5206\u4eab\u5230...</h3><p></p></span></div>",mouseleave:function(){l&&(clearTimeout(j),n=!1,j=setTimeout(function(){n||(i.animate({width:30},500),p.animate({right:-120},500,function(){l=!1}))},1E3))},mouseenter:function(){l&&(clearTimeout(j),n=!0)}}).appendTo(c(document.body)),o=i.find("p"),
p=i.find("div"),a=function(){i.css("top",c(window).scrollTop()+b.args.sideBar_top)};c.each(b.args.moreShow,function(){b.addBtn(this,12,5,o,!0,1)});b.addBtn(-1,12,5,o,"\u66f4\u591a...").click(function(){b.showPanel()});i.find("b").hover(function(){l||(l=!0,i.animate({width:150},500),p.animate({right:0},500))});i.find("button").click(function(){p.animate({right:-150},500,function(){i.remove()})}).hover(function(){c(this).addClass("hover")},function(){c(this).removeClass("hover")});c.browser.msie&&c.browser.msie<=
6?(c(window).scroll(a),a()):i.css({position:"fixed",top:b.args.sideBar_top})}else if(a==4&&b.args.imgs){var a="NIE-share-img",g=c("#"+a),d=g.length>0,q,r=!1,m=function(a){return b.args.imgSize[0]<a.outerWidth()&&b.args.imgSize[1]<a.outerHeight()};c(b.args.imgs).hover(function(){var a=c(this),e=a.outerHeight(),d=a.offset(),f=c(window),h=g.outerHeight();if(m(a))clearTimeout(q),r=!0,b.args.img=x(a.attr("src")).href,g.find(".NIE-share-more>span").hide(),g.css({top:d.top+e>f.scrollTop()+f.height()?d.top+
10:d.top+e-10-h,left:d.left+10}).show()},function(){var a=c(this);m(a)&&(r=!1,clearTimeout(q),q=setTimeout(function(){r||g.hide()},500))});b.args.defShow=b.args.defShow2;if(!d)g=c("<div>",{id:a,mouseenter:function(){clearTimeout(q);r=!0},mouseleave:function(){r=!1;clearTimeout(q);q=setTimeout(function(){r||g.hide()},500)}}).appendTo(c(document.body)),b.args.type=1,b.args.fat=g,arguments.callee()}else if(a==5&&b.args.txt){var a="NIE-share-txt",g=c("#"+a),d=g.length>0,w=!1,v=c(b.args.txt),u=function(){var a=
"";if(window.getSelection)a=window.getSelection();else if(document.getSelection)a=document.getSelection();else if(document.selection)a=document.selection.createRange().text;return c.trim(a)};b.args.defShow=b.args.defShow2;if(!d)g=c("<div>",{id:a}).appendTo(c(document.body)),v.mouseup(function(a){setTimeout(function(){var d=c.trim(u());w&&d!=""?(b.args.content=b.args.title=d,g.css({top:a.pageY+15,left:a.pageX-50}).show()):g.hide()},100)}).mouseleave(function(){w=!1}).mouseenter(function(){w=!0}),c(document.body).mouseup(function(){!w&&
c.trim(u())==""&&g.hide()}),b.args.type=1,b.args.fat=g,arguments.callee()}else a==6&&c.each(b.args.defShow,function(){b.addBtn(this,16,0,b.args.fat,!0,1)})}};b.init=function(){if(location.search!=""&&!nie.util.share_traceCome){var a=location.search.match(b.args.urlReg);if(a)nie.util.share_traceCome=!0,v("http://click.ku.163.com/share.income.gif?"+["id="+a[2],"product="+a[3],"type="+a[4],"_r="+(new Date).getMilliseconds()].join("&"))}a=[[22,"\u6613\u4fe1","YiXin","news.163.com/special/yixin-share/",
{1:"url",2:"title",3:"image",4:"desc"},{source:encodeURIComponent("\u7f51\u6613\u6e38\u620f")}],[1,"QQ\u7a7a\u95f4","QQKongJian","sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey",{1:"url",2:"title",3:"pics",4:"desc"}],[2,"\u65b0\u6d6a\u5fae\u535a","XinLangWeiBo","v.t.sina.com.cn/share/share.php",{1:"url",2:"title",3:"pic"},{c:"nie",content:"gb2312",source:"nie"}],[3,"\u817e\u8baf\u5fae\u535a","TengXunWeiBo","v.t.qq.com/share/share.php",{1:"url",2:"title",3:"pic"}],[4,"\u817e\u8baf\u670b\u53cb",
"TengXunPengYou","sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey",{1:"url",2:"title",3:"pics",4:"desc"},{to:"pengyou"}],[5,"\u7f51\u6613\u5fae\u535a","WangYiWeiBo","t.163.com/article/user/checkLogin.do",{1:"link",2:"info",3:"images",5:"source"},{check1stImg:!0,togImg:!0,key:"OELT16LMxo0rAmtO"}],[6,"\u641c\u72d0\u5fae\u535a","SouHuWeiBo","t.sohu.com/third/post.jsp",{1:"url",2:"title",3:"pic"},{content:"utf-8"}],[7,"\u5f00\u5fc3\u7f51","KaiXinWang","www.kaixin001.com/repaste/share.php",{1:"rurl",
2:"rtitle",4:"rcontent"}],[8,"\u4eba\u4eba\u7f51","RenRenWang","share.renren.com/share/buttonshare.do",{1:"link",2:"title"}],[9,"\u641c\u72d0\u767d\u793e\u4f1a","SouHuBaiSheHui","bai.sohu.com/share/blank/add.do",{1:"link",2:"title"}],[10,"\u6dd8\u6c5f\u6e56","TaoJiangHu","share.jianghu.taobao.com/share/addShare.htm",{1:"url",2:"title",4:"content"}],[11,"\u8c46\u74e3","DouBan","www.douban.com/recommend/",{1:"url",2:"title",3:"image"}],[13,"\u767e\u5ea6Hi","BaiDuHi","apps.hi.baidu.com/share/",{1:"url",
2:"title",4:"content"}],[14,"\u767e\u5ea6\u8d34\u5427","BaiDuTieBa","tieba.baidu.com/i/app/open_share_api",{1:"link"}],[15,"\u767e\u5ea6\u641c\u85cf","BaiDuShouChang","cang.baidu.com/do/add",{1:"iu",2:"it",4:"dc"},{fr:"ien"}],[16,"\u996d\u5426","FangFou","fanfou.com/sharer",{1:"u",2:"t",4:"d"}],[17,"MSN","Msn","profile.live.com/badge",{1:"url",2:"title",3:"screenshot",4:"description"},{wa:"wsignin1.0"}],[18,"\u5929\u6daf\u793e\u533a","TianYaSheQu","share.tianya.cn/openapp/restpage/activity/appendDiv.jsp",
{1:"ccUrl",2:"ccTitle",4:"ccBody"}],[19,"\u51e4\u51f0\u7f51\u5fae\u535a","FengHuangWangWeiBo","t.ifeng.com/interface.php",{1:"sourceUrl",2:"title",3:"pic"},{_c:"share",_a:"share"}],[20,"139\u8bf4\u5ba2","139ShuoKe","shequ.10086.cn/share/share.php",{1:"tourl",2:"title"}],[21,"\u68a6\u5e7b\u4eba\u751f","MengHuanRenSheng","dream.163.com/share/link/",{1:"url",2:"title",4:"content"}]];if(!nie.util.share_css)c.include("http://res.nie.netease.com/comm/js/nie/util/share/share.v2.css"),nie.util.share_css=
!0;var d=arguments;if(d.length>0&&d[0].length>0){var d=d[0][0],e;for(e in d)typeof d[e]!="undefined"&&(b.args[e]=d[e])}e=0;for(d=a.length;e<d;e++){var f=a[e];b.data[f[0]]={name:f[1],searchTxt:f[2],file:f[3],paramName:f[4],params:typeof f[5]!="undefined"?f[5]:{}}}b.render()}(arguments);return b}})(jQuery);
